
name: 书旗小说
on:
  workflow_dispatch:
  schedule:
     - cron: '50 3,22 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        WXQD: ${{ secrets.WXQD }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【书旗小说】'
        if: env.WXQD
        run: |
          node sss.js